language: node_js
node_js:
  - "13.8.0"
branches:
  only:
    - master
build:
  run:
    - yarn test
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search